name: .net restore and build

on: 
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths:
      - 'CICD/application/*'

jobs:
  build:

    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          - dotnet-verion: '6.0.x'
      - run: dotnet restore 'CICD/application/Apps.sln'
      - run: dotnet build 'CICD/application/Apps.sln' --no-restore
    
